steps:
  # Install dependencies
  #- name: python
   # entrypoint: pip
    #args: ["install", "-r", "requirements.txt", "--user"]

  ~#-name: run-code
   #entrypoint:cd
   #args:["flask"]
  
  #-name: run-flask-app
   #entrypoint: python
   #args: ["app.py"]
   
   
  - id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:    
        terraform apply -auto-approve
